# Generated by Django 2.2.16 on 2020-11-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '博客列表', 'verbose_name_plural': '博客列表'},
        ),
    ]
