# Generated by Django 2.2.16 on 2020-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_alipay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='order_id',
            field=models.CharField(max_length=50, verbose_name='打赏订单号'),
        ),
    ]
